// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WeatherQueryHistory struct {
	ID          int32              `db:"id" json:"id"`
	City        string             `db:"city" json:"city"`
	QueryTime   pgtype.Timestamptz `db:"query_time" json:"query_time"`
	WeatherData []byte             `db:"weather_data" json:"weather_data"`
}
