// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetRecentWeather(ctx context.Context, arg GetRecentWeatherParams) ([]WeatherQueryHistory, error)
	GetWeatherByLocation(ctx context.Context, city string) (WeatherQueryHistory, error)
	InsertWeatherQuery(ctx context.Context, arg InsertWeatherQueryParams) (WeatherQueryHistory, error)
}

var _ Querier = (*Queries)(nil)
